In [24]:
#Experiment-11: Create NumPy arrays with different methods (lists, zeros, ones, arange). 


import numpy as np
#zero
arr1 = np.zeros((2,3))
print(arr1)




#list
list1 = [1,2,4,5]
list2 = [6,7,8,9]
arr2=np.array([list1,list2])
print(arr2)





#ones
arr4 = np.ones((3,4))
print(arr4)




#arange
arr5=np.arange(1,50,2)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 2 4 5]
 [6 7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [31]:
# Perform mathematical operations on NumPy arrays (addition, subtraction, multiplication, division).
arr1=np.array([1,2,5,6])
arr2=np.array([3,4,7,8])

print("Addition",arr1+arr2)
print("Substraction",arr1-arr2)
print("Multiplication",arr1*arr2)
print("Division",arr1/arr2)




Addition [ 4  6 12 14]
Substraction [-2 -2 -2 -2]
Multiplication [ 3  8 35 48]
Division [0.33333333 0.5        0.71428571 0.75      ]


In [38]:
# Practice indexing and slicing NumPy arrays.
a=np.arange(20)
s=slice(2,9,3)
print("Slicing",a[s])

#indexing
arr=np.array([[1,3,5],[4,5,6],[7,8,9]])
print("indexing:",arr[1,2])

Slicing [2 5 8]
indexing: 6


In [42]:
from scipy import stats
arr=np.array([6,7,8,9,1,2,3,4,9])

print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Mode:",stats.mode(arr)[0])

Mean: 5.444444444444445
Median: 6.0
Mode: 9


In [43]:
arr = np.array([[1,2],[4,5],[2,7],[8,9]])
print("Reshaped array:\n",arr2)

Reshaped array:
 [3 4 7 8]
